name: Deploy Train Map

on:
  push:
    branches:
      - main # or master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- NEW STEP: Inject API Key ---
      - name: Inject Google Maps API Key
        run: |
          # Use 'sed' to replace the placeholder with the secret value
          # The secret is accessed via the environment variable MAPS_API
          # which is set in the 'env' block below.
          sed -i 's|%API_KEY_PLACEHOLDER%|${{ secrets.MAPS_API }}|g' index.html
        env:
          # This line makes the secret available to the 'run' command as an environment variable
          MAPS_API: ${{ secrets.MAPS_API }}
      # ---------------------------------

      # Step to deploy using GitHub Pages action (example)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./